version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend/source:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_API_URL
      - VUE_APP_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - VUE_APP_CLIENT_ID=${COGNITO_CLIENT_ID}
      - VUE_APP_COGNITO_REGION=${COGNITO_REGION}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - APP_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_REGION=${COGNITO_REGION}